/*---------------------------------*- C++ -*---------------------------------*\
    Compiler Generator Coco/R,
    Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
    extended by M. Loeberbauer & A. Woess, Univ. of Linz
    ported to C++ by Csaba Balazs, University of Szeged
    with improvements
        - Pat Terry, Rhodes University
        - 2010 Mark Olesen
-------------------------------------------------------------------------------
License
    This file is part of Compiler Generator Coco/R

    This program is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2, or (at your option) any
    later version.

    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

    As an exception, it is allowed to write an extension of Coco/R that is
    used as a plugin in non-free software.

    If not otherwise stated, any source code generated by Coco/R (other than
    Coco/R itself) does not fall under the GNU General Public License.
\*---------------------------------------------------------------------------*/

#include <string.h>
#include "BitArray.h"

namespace Coco
{

// * * * * * * * * * * * * * * * * Constructors  * * * * * * * * * * * * * * //

BitArray::BitArray(const int length, const bool defaultValue)
:
	size_(length),
	data_(new unsigned char[(size_+7)>>3])
{
	if (defaultValue)
		memset(data_, 0xFF, (size_+7)>>3);
	else
		memset(data_, 0x00, (size_+7)>>3);
}


BitArray::BitArray(const BitArray &copy)
:
	size_(copy.size_),
	data_(new unsigned char[(size_+7)>>3])
{
	memcpy(data_, copy.data_, (size_+7)>>3);
}


// * * * * * * * * * * * * * * * * Destructor  * * * * * * * * * * * * * * * //

BitArray::~BitArray()
{
	delete[] data_;
	data_ = 0;
}


// * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * * //

int BitArray::size() const
{
	return size_;
}


bool BitArray::Get(const int index) const
{
	return (data_[(index>>3)] & (1 << (index&7))) != 0;
}


void BitArray::Set(const int index, const bool value)
{
	if (value)
	{
		data_[(index>>3)] |= (1 << (index&7));
	}
	else
	{
		data_[(index>>3)] &= ~(1 << (index&7));
	}
}


void BitArray::SetAll(const bool value)
{
	if (value)
		memset(data_, 0xFF, (size_+7)>>3);
	else
		memset(data_, 0x00, (size_+7)>>3);
}


void BitArray::Not()
{
	for (int i=0; i<(size_+7)>>3; ++i)
	{
		data_[i] ^= 0xFF;
	}
}

void BitArray::And(const BitArray& b)
{
	for (int i=0; (i<(size_+7)>>3) && (i<(b.size_+7)>>3); ++i)
	{
		data_[i] &= b.data_[i];
	}
}


void BitArray::Or(const BitArray& b)
{
	for (int i=0; (i<(size_+7)>>3) && (i<(b.size_+7)>>3); ++i)
	{
		data_[i] |= b.data_[i];
	}
}


void BitArray::Xor(const BitArray& b)
{
	for (int i=0; (i<(size_+7)>>3) && (i<(b.size_+7)>>3); ++i)
	{
		data_[i] ^= b.data_[i];
	}
}


bool BitArray::Equal(const BitArray& right) const
{
	if (size_ != right.size_)
	{
		return false;
	}
	for (int i = 0; i < size_; ++i)
	{
		if ((data_[(i>>3)] & (1<<(i&7))) != (right.data_[(i>>3)] & (1<<(i&7))))
		{
			return false;
		}
	}
	return true;
}


// * * * * * * * * * * * * * * Member Operators  * * * * * * * * * * * * * * //

BitArray& BitArray::operator=(const BitArray& right)
{
	if (this != &right)          // avoid self assignment
	{
		delete[] data_;           // prevents memory leak
		size_ = right.size_;
		data_ = new unsigned char[(size_+7)>>3];
		memcpy(data_, right.data_, (size_+7)>>3);
	}
	return *this;   // enables cascaded assignments
}


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Coco

// ************************************************************************* //
