/*---------------------------------*- C++ -*---------------------------------*\
    Compiler Generator Coco/R,
    Copyright (c) 2010 Mark Olesen
-------------------------------------------------------------------------------
License
    This file is part of Compiler Generator Coco/R

    This program is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2, or (at your option) any
    later version.

    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

    As an exception, it is allowed to write an extension of Coco/R that is
    used as a plugin in non-free software.

    If not otherwise stated, any source code generated by Coco/R (other than
    Coco/R itself) does not fall under the GNU General Public License.
\*---------------------------------------------------------------------------*/

/*!
 * @file CocoInfo.h
 * @brief Static version and configuration information.
 *
 * This information could normally be provided by the GNU autoconfig,
 * but do it here manually to avoid dependency on autoconfig
 * (eg, for Windows builds, etc)
 *
 */

#ifndef COCO_INFO_H__
#define COCO_INFO_H__

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#define PACKAGE_DATE   "1 Feb 2010"
#define PACKAGE_URL    "http://www.ssw.uni-linz.ac.at/coco/"


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
