/*---------------------------------*- C++ -*---------------------------------*\
    Compiler Generator Coco/R,
    Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
    extended by M. Loeberbauer & A. Woess, Univ. of Linz
    ported to C++ by Csaba Balazs, University of Szeged
    with improvements by Pat Terry, Rhodes University

    Some portions of code from OpenFOAM - Copyright (C) 2008-2009 OpenCFD Ltd.
-------------------------------------------------------------------------------
License
    This file is part of Compiler Generator Coco/R

    This program is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2, or (at your option) any
    later version.

    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

    As an exception, it is allowed to write an extension of Coco/R that is
    used as a plugin in non-free software.

    If not otherwise stated, any source code generated by Coco/R (other than
    Coco/R itself) does not fall under the GNU General Public License.
\*---------------------------------------------------------------------------*/
#ifndef COCO_HASHTABLE_H__
#define COCO_HASHTABLE_H__

#include <string>
#include <vector>

namespace Coco
{

/*---------------------------------------------------------------------------*\
                          Class HashTable Declaration
\*---------------------------------------------------------------------------*/

//! @brief A simple HashTable implementation
/**
 * @note This hash table is only vaguely STL-like. In accordance with
 * its present purpose, this hash table only supports a constIterator
 * and no deletions. For simplicity, the constIterator increment is
 * simply via a next() method. Instead of comparing to an end value,
 * the constIterator valid() method is used.
 * For example,
 * @code
 *    for
 *    (
 *         HashTable<foo>::constIterator iter = myHash.begin();
 *         iter.valid();
 *         iter.next()
 *    )
 *    {
 *        std::cerr<< "key: " << iter.key() << "\n";
 *    }
 * @endcode
 *
 */
template<class Type, class KeyType=std::wstring>
class HashTable
{
	//! An entry within the HashTable
	struct Entry
	{
		const KeyType key; //<! The lookup key
		Type  *val;        //<! The data
		Entry *next;       //<! Pointer next Entry in sub-list

		Entry(const KeyType& k, Type *v, Entry *n=0)
		:
			key(k), val(v), next(n)
		{}
	};

public:
	class constIterator;        // Forward declaration of constIterator
	friend class constIterator; //!< Declare friendship with constIterator

	//! Construct with a default size
	HashTable(int size = 128);

	~HashTable();

	//! A const iterator for HashTable
	class constIterator
	{
		friend class HashTable;     //!< Declare friendship with HashTable

		//! Pointer to the HashTable for which this is an iterator
		const HashTable<Type, KeyType> *hashTable_;

		//! Current element
		Entry* entryPtr_;

		//! Current hash index
		int hashIndex_;

	public:

		//! Construct from hash table, moving to its 'begin' position
		explicit constIterator(const HashTable<Type, KeyType>* ht);

		//! Return true if iterator is valid (ie, not at the end)
		bool valid() const;

		//! Increment to the next position
		void next();

		//! Return the Key corresponding to the iterator
		const KeyType& key() const;

		//! Return the value corresponding to the iterator
		const Type* value() const;
	};


	//! Insert a new Entry
	void Set(const KeyType& key, Type *value);

	//- Find and return the value associated with the hashed Entry
	Type* Get(const KeyType& key) const;

	//! Return a constIterator to the first entry
	constIterator begin() const;

	//! Return a constIterator to the first matching pointer
	constIterator findPointer(const Type* ptr) const;

	//! Same as the Get() method
	inline Type* operator[](const KeyType& key) const
	{
		return Get(key);
	}

	//! Return table of contents, optionally sorted
	std::vector<KeyType> toc(const bool sorted=false) const;

private:
	const int size_;   //<! fixed HashTable size
	Entry** table_;

	Entry* GetEntry(const KeyType& key) const;

};

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Coco

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#include "HashTable.tcc"

#endif

// ************************************************************************* //
